### ISSUE TITLE
PR: add custom index for user defined characters

### ISSUE THREAD

**Issue by AvinashPudale** [arthursw/BrailleRap#2]
add custom index for user defined characters like numberPrefix: [4, 5, 7, 8],
this allows to add new languages.
for example customPrefix: [4, 6, 7, 8],
defined custom char "a'
                        "a": [1],
which gives output at as  [4, 6, 7, 8] ,[1],
this help to complete  devanagri  language file 
here is my  devnagari webpage files 
[devnagariBraille-master.zip](https://github.com/arthursw/BrailleRap/files/2825882/devnagariBraille-master.zip)

**Comment by crocsg** [comment]
Hello Avinash 
i'm not sure i understand, you need to change the Braille representation prefix for number ? if so do we need to change something in number detection ? ie we are using 123456789, i'm not sure you are using it in devanagri. 

Another question, do you need it for your BrailleRAP-SP, or do you need it for a standard 3D printer ? The repository for BraillerapSP is in https://github.com/crocsg/BrailleRap. We had some discussion with Arthur to merge the 2 versions, but we have not take the time to dot it at this time.

Stephane from BrailleRAP-SP team

**Comment by AvinashPudale** [comment]
Yes I need for BrailleRapSp.  Yes .  need prefix for number as well as char .  This  helps lot to devnagari.

**Comment by AvinashPudale** [comment]
May be i not push right updated data to repository. So number are no there. Hopeing this feature in future . thanks for quick reply.

**Comment by arthursw** [comment]
I don't really understand your request.

The way to add a new language is pretty straight forward: 
 - just create a new language file (copy "braille6.js", "braille8old.js" or "braille8new.js" and change it with chars and the number prefix you want),
 - include it in index.html,
 - you should now be able to select your new language in the gui.

Note: maybe you request is having multiple language prefixes for the same language? 
This would be a major change in the code.

Instead, as a quick fix, you could just choose two (or more) characters that would correspond to your prefixes. The user would have to type one of those characters before writing the number they want.

**Comment by crocsg** [comment]
Hello Arthur,
has i understand, in devnagari Braille, some black characters are translated in 2 Brailles characters.
There is maybe also a number detection issue.
see https://en.wikipedia.org/wiki/Bharati_Braille

**Comment by arthursw** [comment]
I see, so the easiest way is that the user types two characters for those special devnagari Braille chars.

**Comment by AvinashPudale** [comment]
I made  modification . And it works i need to know  whare is posted. In which repository.
