### ISSUE TITLE
Off-line?

### ISSUE THREAD

**Issue by JohnInWI** [arthursw/BrailleRap#3]
Hello and thanks for a very useful and interesting project.
I'm trying to run this / and modify off-line. I'm a bit of a noob to JS and HTML, but when I download or clone the files, then open the local index.html with Chrome, the GUI on the right hand side is missing, as is the rendering of the braille output (it's paperCanvas?).

I've tried a few things, un-commenting the web-based js files for paper-full.min.js and dat.gui.min.js and even copying code from your "served" version without success. All the js, html and css files are in the same folder.

Your on-line version works well with the same browser, so I don't think that's the issue.
Maybe you can point me in the right direction?

**Comment by JohnInWI** [comment]
I found a errant (invisible?) character of some sort in line 122 of the script.js. (right before the curly brace)
Deleted whatever is was and now runs flawlessly with the local files....

**Comment by arthursw** [comment]
Thanks! This annoying non-breaking space character, or blank character is often inserted on mac when pressing `option` + `space`. It creates bugs with some tools and is hard to detect. 

Issue fixed.
